# Generated by Django 5.1.2 on 2024-11-20 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(related_name='scheduling_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('referee', models.ForeignKey(blank=True, limit_choices_to={'role': 'referee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refereed_games', to=settings.AUTH_USER_MODEL)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='scheduling.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='scheduling.team')),
            ],
        ),
    ]
